name: Publish to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  process-tokens:
    name: Process tokens
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code from GitHub
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Build the static site
      run: |
        npm ci
        npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build
